window.ACTIVITIES = [
  {
    "id": "arpoador",
    "cat": "Playa",
    "icon": "🏖️",
    "name": "Arpoador + Ipanema",
    "zone": "Arpoador / Ipanema",
    "price": "Gratis",
    "duration": "2–5 h",
    "dist": "3 km",
    "time": "10–15 min",
    "transport": "A pie / bici",
    "ret": "A pie o Uber",
    "info": "Plan comodín perfecto: playa, paseo y atardecer sin gastar casi nada. En los reels aparece como uno de los cierres de día más repetidos.",
    "how": "Desde Copacabana conviene ir caminando por la orla, en bici o con un Uber corto.",
    "safety": "Zona turística y cómoda. Cuidar pertenencias en la arena y no dejar el celular visible sin atención.",
    "tip": "Ideal para primer día, día liviano o como cierre después de otra actividad.",
    "source": "https://riotur.rio/",
    "sourceLabel": "Riotur",
    "profile": "beach",
    "confidence": "Corroborado",
    "steps": [
      "Base en Copacabana",
      "Orla de Copacabana",
      "Arpoador",
      "Ipanema puestos 8–10"
    ]
  },
  {
    "id": "leme",
    "cat": "Playa",
    "icon": "🏖️",
    "name": "Copacabana + Leme",
    "zone": "Copacabana / Leme",
    "price": "Gratis",
    "duration": "2–4 h",
    "dist": "0–3 km",
    "time": "A pie",
    "transport": "A pie / bici",
    "ret": "A pie",
    "info": "La playa base del viaje. Sirve para mañanas tranquilas, primeras horas tras llegar y días en los que no quieren cargar el itinerario.",
    "how": "Caminar por la orla. Para Leme, simplemente seguir hacia el extremo norte de Copacabana.",
    "safety": "Muy turística; precauciones normales con pertenencias y celular.",
    "tip": "Perfecta para meter compras del súper, cerveza fría y un día sin tour.",
    "source": "https://riotur.rio/",
    "sourceLabel": "Riotur",
    "profile": "beach",
    "confidence": "Corroborado",
    "steps": [
      "Base",
      "Copacabana",
      "Leme"
    ]
  },
  {
    "id": "praia_vermelha",
    "cat": "Playa",
    "icon": "🏖️",
    "name": "Praia Vermelha + Urca",
    "zone": "Urca",
    "price": "Gratis",
    "duration": "2–4 h",
    "dist": "5 km",
    "time": "15–25 min",
    "transport": "Uber / bici",
    "ret": "Uber",
    "info": "Playa pequeña y muy linda, ideal para combinar con la Trilha do Morro da Urca o una tarde tranquila.",
    "how": "Uber directo desde Copacabana. También puede hacerse en bici si ya vienen pedaleando por Botafogo/Flamengo.",
    "safety": "Zona cómoda. Si se hace de noche, volver en Uber.",
    "tip": "Muy buena combinación con Bondinho y atardecer.",
    "source": "https://riotur.rio/",
    "sourceLabel": "Riotur",
    "profile": "urca",
    "confidence": "Corroborado",
    "steps": [
      "Base",
      "Botafogo",
      "Urca",
      "Praia Vermelha"
    ]
  },
  {
    "id": "leblon",
    "cat": "Playa",
    "icon": "🏖️",
    "name": "Leblon + Mirante do Leblon",
    "zone": "Leblon",
    "price": "Gratis",
    "duration": "2–4 h",
    "dist": "5 km",
    "time": "15–25 min",
    "transport": "Metro + caminata / bici / Uber",
    "ret": "Metro / Uber",
    "info": "Buena extensión de Ipanema para hacer playa y sumar una caminata hasta el mirador.",
    "how": "Metro hasta Jardim de Alah/Antero de Quental según punto, o bici por la orla.",
    "safety": "Zona cómoda de día y tarde.",
    "tip": "Funciona excelente en un día de playa sin tours.",
    "source": "https://riotur.rio/",
    "sourceLabel": "Riotur",
    "profile": "beach",
    "confidence": "Corroborado",
    "steps": [
      "Base",
      "Ipanema",
      "Leblon",
      "Mirante do Leblon"
    ]
  },
  {
    "id": "bondinho",
    "cat": "Naturaleza",
    "icon": "🥾",
    "name": "Pão de Açúcar + Trilha do Morro da Urca",
    "zone": "Urca / Praia Vermelha",
    "price": "R$65 bajada / R$140 trilha + Pão",
    "duration": "3–5 h",
    "dist": "5 km",
    "time": "15–25 min",
    "transport": "Uber",
    "ret": "Uber",
    "info": "Subir caminando al Morro da Urca y decidir arriba si pagan solo la bajada o continúan al Pão de Açúcar. Fue uno de los mejores hacks de ahorro encontrados.",
    "how": "Uber hasta Praia Vermelha. La trilha funciona de día y la bajada en bondinho no es gratis.",
    "safety": "Zona tranquila. No hacer la trilha con lluvia o cuando ya está cerrando el acceso.",
    "tip": "Gran plan para tarde + atardecer. El acceso por trilha se corroboró en la web oficial del Bondinho.",
    "source": "https://sac.bondinho.com.br/hc/pt-br/articles/9818455162395-Acesso-ao-Parque-Bondinho-pela-trilha-do-Morro-da-Urca",
    "sourceLabel": "Parque Bondinho · oficial",
    "profile": "urca",
    "confidence": "Oficial",
    "steps": [
      "Base",
      "Praia Vermelha",
      "Pista Cláudio Coutinho",
      "Trilha Morro da Urca",
      "Morro da Urca",
      "Pão de Açúcar"
    ]
  },
  {
    "id": "cristo",
    "cat": "Cultura",
    "icon": "🏛️",
    "name": "Cristo Redentor · Trem do Corcovado",
    "zone": "Corcovado / Cosme Velho",
    "price": "R$134 tren (referencia 2026)",
    "duration": "3–4 h",
    "dist": "8 km",
    "time": "25–35 min",
    "transport": "Uber + tren",
    "ret": "Uber",
    "info": "El clásico. Conviene comprar en la web oficial y mover el día si el cielo está muy cerrado.",
    "how": "Uber a Cosme Velho y tren oficial. No comprar a revendedores en la calle.",
    "safety": "Ruta turística estándar. El principal riesgo es pagar de más o ir con mala visibilidad.",
    "tip": "Hacerlo temprano para evitar calor y maximizar chance de cielo limpio.",
    "source": "https://www.tremdocorcovado.rio/",
    "sourceLabel": "Trem do Corcovado · oficial",
    "profile": "christ",
    "confidence": "Oficial",
    "steps": [
      "Base",
      "Cosme Velho",
      "Trem do Corcovado",
      "Cristo Redentor"
    ]
  },
  {
    "id": "jardim",
    "cat": "Naturaleza",
    "icon": "🥾",
    "name": "Jardim Botânico",
    "zone": "Jardim Botânico",
    "price": "Revisar tarifa vigente",
    "duration": "2–3 h",
    "dist": "6 km",
    "time": "15–25 min",
    "transport": "Uber",
    "ret": "Uber / bici Lagoa",
    "info": "Mañana tranquila y fotogénica. Se combina perfecto con Parque Lage y Lagoa.",
    "how": "Uber directo. Desde Ipanema también puede encajar con bici por Lagoa.",
    "safety": "Zona cómoda de día.",
    "tip": "Buen día para bajar revoluciones entre noches fuertes.",
    "source": "https://www.gov.br/jbrj/pt-br/assuntos/visitacao/horarios-e-ingressos",
    "sourceLabel": "Jardim Botânico · oficial",
    "profile": "garden",
    "confidence": "Oficial",
    "steps": [
      "Base",
      "Lagoa",
      "Jardim Botânico"
    ]
  },
  {
    "id": "parque_lage",
    "cat": "Naturaleza",
    "icon": "🥾",
    "name": "Parque Lage",
    "zone": "Jardim Botânico",
    "price": "Gratis / consumo opcional",
    "duration": "1–2 h",
    "dist": "5 km",
    "time": "15–20 min",
    "transport": "Uber / bici",
    "ret": "Uber",
    "info": "Patio fotogénico, café y vista al Cristo. Gran complemento del Jardim Botânico.",
    "how": "Uber desde Copacabana o combinar a pie desde Jardim Botânico.",
    "safety": "Cómodo de día.",
    "tip": "Perfecto como bloque breve antes o después del Jardín.",
    "source": "https://parquelage.org.br/",
    "sourceLabel": "Parque Lage",
    "profile": "garden",
    "confidence": "Corroborado",
    "steps": [
      "Base",
      "Lagoa",
      "Parque Lage"
    ]
  },
  {
    "id": "lagoa",
    "cat": "Naturaleza",
    "icon": "🚲",
    "name": "Lagoa Rodrigo de Freitas · paseo / bici",
    "zone": "Lagoa",
    "price": "Gratis + alquiler opcional",
    "duration": "1–3 h",
    "dist": "4–6 km",
    "time": "15–25 min",
    "transport": "Bici / Uber",
    "ret": "Bici / Uber",
    "info": "Muy buen circuito para bici, caminar o meter una pausa entre Parque Lage, Jardim Botânico e Ipanema.",
    "how": "Llegar en Uber o conectar con bici desde Ipanema/Leblon.",
    "safety": "Cómodo de día y tarde.",
    "tip": "De los mejores usos para movilidad liviana en Río.",
    "source": "https://riotur.rio/",
    "sourceLabel": "Riotur",
    "profile": "garden",
    "confidence": "Corroborado",
    "steps": [
      "Base",
      "Ipanema",
      "Lagoa"
    ]
  },
  {
    "id": "telegrapho",
    "cat": "Naturaleza",
    "icon": "🥾",
    "name": "Pedra do Telégrafo",
    "zone": "Barra de Guaratiba",
    "price": "Gratis + traslado",
    "duration": "6–8 h",
    "dist": "Lejos",
    "time": "50 min–2 h según tráfico",
    "transport": "Uber / tour",
    "ret": "Uber / tour",
    "info": "Trekking de la foto viral. La foto es una ilusión óptica; no hay un precipicio real debajo.",
    "how": "Ir muy temprano hacia Barra de Guaratiba y hacer la subida señalizada. No es una caminata para meter después de una noche pesada.",
    "safety": "El tema principal es calor, tráfico, hidratación y filas, no la actividad en sí.",
    "tip": "Salir 6–7 am, llevar agua y protector, evitar fin de semana si pueden.",
    "source": "https://www.instagram.com/reel/DbeNu6YhrrU/",
    "sourceLabel": "Reel de referencia",
    "profile": "west",
    "confidence": "Reel + corroboración parcial",
    "steps": [
      "Base",
      "Barra de Guaratiba",
      "Inicio de trilha",
      "Pedra do Telégrafo"
    ]
  },
  {
    "id": "dois_irmaos",
    "cat": "Naturaleza",
    "icon": "🥾",
    "name": "Morro Dois Irmãos · hike",
    "zone": "Vidigal",
    "price": "Variable / bajo",
    "duration": "3–5 h",
    "dist": "8 km",
    "time": "25–35 min",
    "transport": "Uber + acceso local",
    "ret": "Uber",
    "info": "Hike con vista fuerte sobre Leblon/Ipanema. Apareció como recomendación recurrente en itinerarios de viajeros.",
    "how": "Llegar al acceso del Vidigal en Uber y resolver la subida inicial con transporte local si corresponde.",
    "safety": "Ir con el objetivo definido, de día y preferentemente con información actualizada del acceso.",
    "tip": "No mezclar con salida nocturna fuerte la noche anterior.",
    "source": "https://riotur.rio/",
    "sourceLabel": "Riotur / referencia general",
    "profile": "vidigal",
    "confidence": "Por verificar cerca del viaje",
    "steps": [
      "Base",
      "Vidigal",
      "Acceso local",
      "Inicio de trilha",
      "Morro Dois Irmãos"
    ]
  },
  {
    "id": "museu",
    "cat": "Cultura",
    "icon": "🏛️",
    "name": "Museu do Amanhã",
    "zone": "Praça Mauá / Centro",
    "price": "R$40 (referencia 2026)",
    "duration": "2–3 h",
    "dist": "10 km",
    "time": "25–35 min",
    "transport": "Metro + VLT / Uber",
    "ret": "Uber si es tarde",
    "info": "Museo moderno que combina muy bien con Boulevard Olímpico y Centro.",
    "how": "De día, metro + VLT funciona muy bien. Si terminan tarde, Uber de regreso.",
    "safety": "Perfecto de día. De noche la zona portuaria requiere más atención.",
    "tip": "Ideal para día nublado o de descanso de playa.",
    "source": "https://museudoamanha.org.br/visite",
    "sourceLabel": "Museu do Amanhã · oficial",
    "profile": "center",
    "confidence": "Oficial",
    "steps": [
      "Base",
      "Centro",
      "VLT",
      "Praça Mauá",
      "Museu do Amanhã"
    ]
  },
  {
    "id": "santa_teresa",
    "cat": "Cultura",
    "icon": "🏛️",
    "name": "Santa Teresa + Escadaria Selarón + Lapa",
    "zone": "Santa Teresa / Lapa",
    "price": "Gratis / transporte",
    "duration": "3–5 h",
    "dist": "8–10 km",
    "time": "25–35 min",
    "transport": "Uber / metro + caminata",
    "ret": "Uber",
    "info": "Circuito cultural muy fotogénico: Santa Teresa, Selarón y Lapa.",
    "how": "Mejor hacerlo de mañana/tarde. Uber o combinación de metro + caminata en tramos con movimiento.",
    "safety": "No dejar la vuelta para caminar de madrugada por calles vacías de Lapa.",
    "tip": "Se puede combinar con Centro si arrancan temprano.",
    "source": "https://riotur.rio/",
    "sourceLabel": "Riotur",
    "profile": "lapa",
    "confidence": "Corroborado",
    "steps": [
      "Base",
      "Santa Teresa",
      "Escadaria Selarón",
      "Arcos da Lapa"
    ]
  },
  {
    "id": "real_gabinete",
    "cat": "Cultura",
    "icon": "🏛️",
    "name": "Real Gabinete Português de Leitura",
    "zone": "Centro",
    "price": "R$15 visita guiada ref. / revisar agenda",
    "duration": "1–2 h",
    "dist": "9 km",
    "time": "25–35 min",
    "transport": "Metro + caminata",
    "ret": "Metro / Uber",
    "info": "Joyita cultural del Centro, ideal para combinar con Colombo y Museu do Amanhã.",
    "how": "Metro al Centro y caminata corta. Si ya cae la tarde, regresar en Uber.",
    "safety": "Centro de día: bien. Horario tardío: más atención.",
    "tip": "La agenda de visitas guiadas tuvo suspensiones; revalidar cerca de marzo 2027.",
    "source": "https://www.realgabinete.com.br/Agenda/visita-guiada",
    "sourceLabel": "Real Gabinete · agenda",
    "profile": "center",
    "confidence": "Oficial / agenda variable",
    "steps": [
      "Base",
      "Centro",
      "Real Gabinete"
    ]
  },
  {
    "id": "colombo",
    "cat": "Cultura",
    "icon": "☕",
    "name": "Confeitaria Colombo",
    "zone": "Centro / Forte de Copacabana",
    "price": "Consumo según pedido",
    "duration": "1–2 h",
    "dist": "Variable",
    "time": "Depende de sede",
    "transport": "A pie / metro / Uber",
    "ret": "A pie / Uber",
    "info": "Clásico histórico y gastronómico. La sede Centro encaja con circuito cultural; la del Forte encaja con Copacabana.",
    "how": "Centro: metro/VLT. Forte: caminata por la orla desde Copacabana.",
    "safety": "Centro mejor de día; Forte muy cómodo.",
    "tip": "Elegir sede según el día, no hacer un viaje extra solo por la cafetería.",
    "source": "https://www.confeitariacolombo.com.br/",
    "sourceLabel": "Confeitaria Colombo · oficial",
    "profile": "center",
    "confidence": "Oficial",
    "steps": [
      "Base",
      "Centro / Forte",
      "Confeitaria Colombo"
    ]
  },
  {
    "id": "maracana",
    "cat": "Cultura",
    "icon": "⚽",
    "name": "Tour Maracanã",
    "zone": "Maracanã",
    "price": "R$115 ref. compra directa",
    "duration": "1–2 h",
    "dist": "12 km",
    "time": "25–40 min",
    "transport": "Metro / Uber",
    "ret": "Metro / Uber",
    "info": "Opcional si les interesa fútbol. Comprar directo puede ser bastante más barato que intermediarios argentinos.",
    "how": "Metro o Uber. Revisar horario del tour y si hay evento/partido.",
    "safety": "Plan turístico estándar de día.",
    "tip": "No lo pondría como imprescindible si el presupuesto está ajustado.",
    "source": "https://www.tourmaracana.com.br/",
    "sourceLabel": "Tour Maracanã · oficial",
    "profile": "center",
    "confidence": "Oficial",
    "steps": [
      "Base",
      "Metro / Uber",
      "Maracanã"
    ]
  },
  {
    "id": "arraial",
    "cat": "Tour",
    "icon": "🚤",
    "name": "Arraial do Cabo · full day con tour",
    "zone": "Região dos Lagos",
    "price": "R$250+ / comparar operador",
    "duration": "12–14 h",
    "dist": "Muy lejos",
    "time": "Día completo",
    "transport": "Tour con traslado",
    "ret": "Incluido",
    "info": "Full day de playas y barco. Es una de las excursiones grandes que más sentido tiene contratar desde Río.",
    "how": "Lo ideal es tour con pickup desde Río o punto cercano al alojamiento.",
    "safety": "El mayor riesgo es contratar un operador poco claro. Revisar CNPJ/Cadastur, política de devolución y qué incluye.",
    "tip": "Leer bien: almuerzo, tasas, muelle, jardineira, snorkel y política de cancelación.",
    "source": "https://www.civitatis.com/br/rio-de-janeiro/excursao-arraial-cabo/",
    "sourceLabel": "Operador de referencia",
    "profile": "tour",
    "confidence": "Corroborado / comparar operador",
    "steps": [
      "Pickup Río",
      "Ruta dos Lagos",
      "Arraial do Cabo",
      "Barco",
      "Paradas de baño",
      "Almuerzo",
      "Regreso Río"
    ]
  },
  {
    "id": "pontal_diy",
    "cat": "Tour",
    "icon": "🚤",
    "name": "Pontal do Atalaia · lancha colectiva DIY",
    "zone": "Arraial do Cabo",
    "price": "Reel: R$30 por tramo · verificar",
    "duration": "3–5 h dentro de Arraial",
    "dist": "Fuera de Río",
    "time": "Depende traslado a Arraial",
    "transport": "Bus/tour a Arraial + lancha",
    "ret": "Lancha + regreso",
    "info": "Alternativa barata al paseo completo: lancha colectiva desde Praia dos Anjos hacia Pontal do Atalaia.",
    "how": "Primero llegar a Arraial. La lancha del reel salía de la zona de Praia dos Anjos, cerca de la cancha.",
    "safety": "Verificar frecuencia, precio y regreso con el mismo lanchero. No asumir que el precio del reel seguirá igual en 2027.",
    "tip": "Tiene sentido si ya están en Arraial; no reemplaza por sí sola el traslado desde Río.",
    "source": "https://www.instagram.com/reel/DcGjXPDvcT9/",
    "sourceLabel": "Reel de referencia",
    "profile": "tour",
    "confidence": "Reel · revalidar 2027",
    "steps": [
      "Praia dos Anjos",
      "Lancha colectiva",
      "Pontal do Atalaia",
      "Trilha / mirador",
      "Regreso"
    ]
  },
  {
    "id": "ilha_grande",
    "cat": "Tour",
    "icon": "🚤",
    "name": "Ilha Grande / Angra · full day",
    "zone": "Costa Verde",
    "price": "R$200–300+ + traslado según operador",
    "duration": "12–14 h",
    "dist": "Muy lejos",
    "time": "Día completo",
    "transport": "Tour con transfer / barco",
    "ret": "Incluido según tour",
    "info": "Excursión de naturaleza y agua. Conviene revisar si el precio ya incluye traslado desde Río o solo paseo desde Angra/Ilha Grande.",
    "how": "Tour completo con pickup o traslado independiente + embarcación.",
    "safety": "Revisar clima, inclusiones y punto real de salida.",
    "tip": "No combinar con una salida fuerte la noche anterior.",
    "source": "https://www.civitatis.com/br/rio-de-janeiro/excursao-angra-ilha-grande/",
    "sourceLabel": "Operador de referencia",
    "profile": "tour",
    "confidence": "Corroborado / comparar operador",
    "steps": [
      "Pickup Río",
      "Costa Verde",
      "Embarcación",
      "Paradas de baño",
      "Regreso"
    ]
  },
  {
    "id": "acaia",
    "cat": "Tour",
    "icon": "🌌",
    "name": "Ilha Grande · Gruta de Acaiá + Lagoas",
    "zone": "Ilha Grande",
    "price": "R$200–300+ según agencia",
    "duration": "Día completo",
    "dist": "Fuera de Río",
    "time": "Full day / posible noche en isla",
    "transport": "Transfer + barco",
    "ret": "Transfer / barco",
    "info": "Recorrido del reel: Lagoa Azul, Praia Grumixama, Lagoa Verde y Gruta de Acaiá. La cueva tiene un efecto turquesa por entrada/rebote de luz; no es bioluminiscencia real.",
    "how": "Necesita operador local y logística de llegada a Ilha Grande/Angra.",
    "safety": "La cueva tiene pasaje angosto y agua; seguir instrucciones del guía y verificar condiciones del día.",
    "tip": "Muy atractiva, pero logísticamente bastante más compleja que Arraial para un viaje corto.",
    "source": "https://www.instagram.com/reel/DVj2PRBElJC/",
    "sourceLabel": "Reel + agencia mencionada",
    "profile": "tour",
    "confidence": "Reel / revalidar operador",
    "steps": [
      "Transfer Costa Verde",
      "Ilha Grande",
      "Lagoa Azul",
      "Praia Grumixama",
      "Lagoa Verde",
      "Gruta de Acaiá"
    ]
  },
  {
    "id": "pedra",
    "cat": "Noche",
    "icon": "🌙",
    "name": "Pedra do Sal",
    "zone": "Saúde · Pequena África",
    "price": "Gratis + consumo",
    "duration": "3–5 h",
    "dist": "9 km",
    "time": "20–30 min",
    "transport": "Uber recomendado",
    "ret": "Uber",
    "info": "Samba callejero, puestos de caipirinha y una de las noches más auténticas y baratas de Río. Lunes y viernes son los días más nombrados.",
    "how": "De día puede ser metro/VLT + caminata corta. Para la noche, Uber directo simplifica mucho.",
    "safety": "La zona funciona muy bien con movimiento; no conviene terminar caminando por calles vacías de Saúde/Porto.",
    "tip": "Llegar temprano, riñonera cruzada y volver en Uber.",
    "source": "https://pedradosal.rio.br/",
    "sourceLabel": "Pedra do Sal · guía local",
    "profile": "night",
    "confidence": "Corroborado",
    "steps": [
      "Base",
      "Saúde",
      "Pedra do Sal",
      "Uber regreso"
    ]
  },
  {
    "id": "pagode_garagem",
    "cat": "Noche",
    "icon": "🌙",
    "name": "Pagode da Garagem",
    "zone": "Praça Tiradentes · Centro",
    "price": "Desde R$5 colaborativo (ref. 2026)",
    "duration": "4–6 h",
    "dist": "9 km",
    "time": "25–35 min",
    "transport": "Uber",
    "ret": "Uber",
    "info": "Pagode/samba muy barato y auténtico. El sitio oficial publicaba martes 18:00–03:00 con cortesías y entrada colaborativa.",
    "how": "Uber directo o transporte de ida mientras aún hay flujo. Vuelta en Uber.",
    "safety": "Centro de madrugada: no conviene salir caminando sin rumbo.",
    "tip": "De las mejores noches costo/experiencia de toda la investigación.",
    "source": "https://pagodedagaragem.com/",
    "sourceLabel": "Pagode da Garagem · oficial",
    "profile": "centerNight",
    "confidence": "Oficial / agenda 2027 pendiente",
    "steps": [
      "Base",
      "Praça Tiradentes",
      "Pagode da Garagem",
      "Uber regreso"
    ]
  },
  {
    "id": "bosque",
    "cat": "Noche",
    "icon": "🌙",
    "name": "Bosque Bar",
    "zone": "Gávea / Jockey Club",
    "price": "Entrada variable + consumo",
    "duration": "4–6 h",
    "dist": "8 km",
    "time": "20–30 min",
    "transport": "Uber recomendado",
    "ret": "Uber",
    "info": "Open air, DJs, bailarines y programación distinta según el día. Ideal para una noche más de boliche.",
    "how": "Uber directo desde Copacabana. No vale la pena complicarlo con transporte público de noche.",
    "safety": "El lugar en sí es cómodo; lo importante es resolver bien ida y vuelta.",
    "tip": "Revisar agenda antes de ir y reservar si el evento pinta fuerte.",
    "source": "https://www.barbosquebar.com/programacao",
    "sourceLabel": "Bosque Bar · oficial",
    "profile": "south",
    "confidence": "Oficial / agenda variable",
    "steps": [
      "Base",
      "Gávea",
      "Bosque Bar",
      "Uber regreso"
    ]
  },
  {
    "id": "barzin",
    "cat": "Noche",
    "icon": "🌙",
    "name": "Barzin Ipanema",
    "zone": "Ipanema",
    "price": "Reel: ~R$60 · verificar",
    "duration": "3–5 h",
    "dist": "3–4 km",
    "time": "10–20 min",
    "transport": "Uber corto / metro",
    "ret": "Uber",
    "info": "Bar/boliche de varios pisos: restaurante, lounge y pista. En reels lo recomiendan para cena + fiesta.",
    "how": "Muy cerca desde Copacabana; Uber corto o metro + caminata.",
    "safety": "Hay comentarios divididos sobre el lugar y experiencias negativas; si lo consideran, revisar reseñas recientes y política de cobros antes de ir.",
    "tip": "No lo pondría como prioridad sin revisar comentarios actuales cerca del viaje.",
    "source": "https://www.instagram.com/reel/DdcTWyLO4p6/",
    "sourceLabel": "Reel de referencia",
    "profile": "beachNight",
    "confidence": "Reel / reseñas divididas",
    "steps": [
      "Base",
      "Ipanema",
      "Barzin",
      "Regreso corto"
    ]
  },
  {
    "id": "substation",
    "cat": "Noche",
    "icon": "🌙",
    "name": "Substation Club",
    "zone": "Río · ubicación a revalidar",
    "price": "Reel: ~R$80 · verificar",
    "duration": "4–6 h",
    "dist": "Variable",
    "time": "Variable",
    "transport": "Uber",
    "ret": "Uber",
    "info": "Opción de electrónica mencionada en reels, con shows y ambiente menos comercial que otros boliches.",
    "how": "Confirmar dirección y evento exacto antes de salir.",
    "safety": "No usar este dato sin revalidar agenda y ubicación 2027.",
    "tip": "Candidato de electrónica, pero hoy tiene menor nivel de certeza que D-Edge.",
    "source": "https://www.instagram.com/reel/DdcTWyLO4p6/",
    "sourceLabel": "Reel de referencia",
    "profile": "night",
    "confidence": "Por verificar",
    "steps": [
      "Base",
      "Venue confirmado 2027",
      "Substation",
      "Uber regreso"
    ]
  },
  {
    "id": "mirante_rocinha",
    "cat": "Noche",
    "icon": "🌃",
    "name": "Mirante Rocinha",
    "zone": "Rocinha",
    "price": "Entrada colaborativa / evento variable",
    "duration": "2–4 h",
    "dist": "8–9 km",
    "time": "25–35 min",
    "transport": "Uber + acceso local",
    "ret": "Uber",
    "info": "Vista fuerte sobre Río y plan distinto. El reel hablaba de R$100 + mototaxi; la web actual usa concepto de entrada colaborativa y programación variable.",
    "how": "Uber hasta el acceso indicado por el lugar; si el evento usa mototaxi, tomarlo solo como parte de la logística del venue.",
    "safety": "Ir directo al mirante y volver directo. No usarlo como excusa para improvisar por calles internas.",
    "tip": "Muy interesante si buscan algo distinto, pero con logística clara.",
    "source": "https://www.miranterocinha.com.br/",
    "sourceLabel": "Mirante Rocinha · oficial",
    "profile": "rocinha",
    "confidence": "Oficial / precio variable",
    "steps": [
      "Base",
      "Acceso Rocinha",
      "Mirante Rocinha",
      "Uber regreso"
    ]
  },
  {
    "id": "arvrao",
    "cat": "Noche",
    "icon": "🌃",
    "name": "Mirante do Arvrão",
    "zone": "Vidigal",
    "price": "Evento / consumo variable",
    "duration": "3–5 h",
    "dist": "8 km",
    "time": "25–35 min",
    "transport": "Uber + acceso local",
    "ret": "Uber",
    "info": "Sunset/night spot conocido en Vidigal, con vista panorámica y programación variable.",
    "how": "Uber hasta Vidigal + acceso indicado por el lugar.",
    "safety": "Misma lógica que Rocinha: destino claro, sin improvisar caminatas nocturnas.",
    "tip": "Muy bueno como sunset antes de que se haga demasiado tarde.",
    "source": "https://mirantedoarvrao.com.br/wp/",
    "sourceLabel": "Mirante do Arvrão · oficial",
    "profile": "vidigal",
    "confidence": "Oficial / agenda variable",
    "steps": [
      "Base",
      "Vidigal",
      "Mirante do Arvrão",
      "Uber regreso"
    ]
  },
  {
    "id": "visao_vidigal",
    "cat": "Noche",
    "icon": "🌃",
    "name": "Visão Vidigal",
    "zone": "Vidigal",
    "price": "R$40–80 aprox según evento",
    "duration": "4–6 h",
    "dist": "8 km",
    "time": "25–35 min",
    "transport": "Uber + acceso local",
    "ret": "Uber",
    "info": "Rooftop/fiestas/sunset con eventos de funk, electrónica y reggae. Se encontraron múltiples eventos recientes en plataformas de tickets.",
    "how": "Uber hasta el acceso y seguir instrucciones del evento.",
    "safety": "Revalidar evento puntual y regreso antes de salir.",
    "tip": "Gran candidato para noche especial si coincide una fecha fuerte.",
    "source": "https://shotgun.live/en/venues/visao-vidigal",
    "sourceLabel": "Eventos Visão Vidigal",
    "profile": "vidigal",
    "confidence": "Activo / agenda variable",
    "steps": [
      "Base",
      "Vidigal",
      "Visão",
      "Uber regreso"
    ]
  },
  {
    "id": "dedge",
    "cat": "Noche",
    "icon": "🎧",
    "name": "D-Edge Rio",
    "zone": "Saúde / Porto",
    "price": "R$80–150 aprox según fecha",
    "duration": "6–8 h",
    "dist": "10 km",
    "time": "25–35 min",
    "transport": "Uber",
    "ret": "Uber",
    "info": "Club fuerte de electrónica. En eventos recientes aparece con dirección estable en la zona portuaria y horario de madrugada.",
    "how": "Uber ida y vuelta.",
    "safety": "No salir caminando por la zona portuaria a las 5–7 am.",
    "tip": "Elegirlo solo si realmente quieren una noche larga y electrónica.",
    "source": "https://ra.co/clubs/217021",
    "sourceLabel": "RA · D-Edge Rio",
    "profile": "centerNight",
    "confidence": "Activo / evento variable",
    "steps": [
      "Base",
      "Saúde",
      "D-Edge",
      "Uber regreso"
    ]
  },
  {
    "id": "canastra",
    "cat": "Noche",
    "icon": "🌙",
    "name": "Canastra Rosé",
    "zone": "Botafogo",
    "price": "Reel: R$60–100 · verificar",
    "duration": "3–5 h",
    "dist": "4 km",
    "time": "15–20 min",
    "transport": "Metro / Uber",
    "ret": "Uber",
    "info": "Lugar de varios pisos con mezcla de reggaetón, latino y música brasileña; reel lo propone como opción para bailar.",
    "how": "Metro o Uber corto a Botafogo.",
    "safety": "Zona cómoda; igual revisar agenda real 2027.",
    "tip": "Buena opción si quieren música más latina que electrónica pura.",
    "source": "https://www.instagram.com/reel/DVemauGjoIW/",
    "sourceLabel": "Reel de referencia",
    "profile": "south",
    "confidence": "Reel / revalidar",
    "steps": [
      "Base",
      "Botafogo",
      "Canastra Rosé",
      "Uber regreso"
    ]
  },
  {
    "id": "boa_praca",
    "cat": "Noche",
    "icon": "🍻",
    "name": "Boteco Boa Praça",
    "zone": "Leblon",
    "price": "Consumo R$50–100 aprox",
    "duration": "2–4 h",
    "dist": "5 km",
    "time": "15–25 min",
    "transport": "Uber / metro",
    "ret": "Uber / metro",
    "info": "Resto-bar colorido con música en vivo, ambiente social y buena opción para grupo.",
    "how": "Uber o metro + caminata por Leblon.",
    "safety": "Zona cómoda.",
    "tip": "Más bar/previa que boliche; ideal para noche liviana.",
    "source": "https://botecoboapraca.com.br/",
    "sourceLabel": "Boa Praça · oficial",
    "profile": "beachNight",
    "confidence": "Activo",
    "steps": [
      "Base",
      "Leblon",
      "Boa Praça",
      "Regreso"
    ]
  },
  {
    "id": "brewteco",
    "cat": "Noche",
    "icon": "🍻",
    "name": "Brewteco Botafogo · Terraço",
    "zone": "Botafogo",
    "price": "Consumo moderado",
    "duration": "2–4 h",
    "dist": "4 km",
    "time": "15–20 min",
    "transport": "Metro / Uber",
    "ret": "Metro / Uber",
    "info": "Rooftop relativamente económico con vista a la Bahía y Pão de Açúcar. En reel apareció como el rooftop más barato de cuatro.",
    "how": "Metro a Botafogo + caminata, o Uber corto.",
    "safety": "Zona cómoda; si vuelven tarde, Uber.",
    "tip": "Muy buen plan de atardecer/previa.",
    "source": "https://brewteco.com.br/brew-botafogo/",
    "sourceLabel": "Brewteco · oficial",
    "profile": "south",
    "confidence": "Oficial / consumo variable",
    "steps": [
      "Base",
      "Botafogo",
      "Brewteco",
      "Regreso"
    ]
  },
  {
    "id": "fairmont",
    "cat": "Noche",
    "icon": "🌇",
    "name": "Spirit Copa Bar · Fairmont",
    "zone": "Copacabana",
    "price": "Consumo premium",
    "duration": "2–3 h",
    "dist": "Cerca",
    "time": "A pie / Uber corto",
    "transport": "A pie / Uber",
    "ret": "A pie / Uber",
    "info": "Rooftop/bar premium con vista. Reel lo presentaba como acceso sin entrada, pagando consumo.",
    "how": "Muy cerca desde Copacabana; caminata por la orla o Uber corto.",
    "safety": "Zona cómoda.",
    "tip": "Capricho opcional, no prioridad en viaje low-cost.",
    "source": "https://www.fairmont.com/es/hotels/rio-de-janeiro/fairmont-rio-de-janeiro-copacabana/dining/spirit-bar.bar.html",
    "sourceLabel": "Fairmont · oficial",
    "profile": "beachNight",
    "confidence": "Oficial / consumo variable",
    "steps": [
      "Base",
      "Posto 6",
      "Fairmont"
    ]
  },
  {
    "id": "hilton",
    "cat": "Noche",
    "icon": "🌇",
    "name": "Isabel Lounge · Hilton Copacabana",
    "zone": "Leme / Copacabana",
    "price": "Consumo premium",
    "duration": "2–3 h",
    "dist": "2–3 km",
    "time": "10–15 min",
    "transport": "A pie / Uber",
    "ret": "A pie / Uber",
    "info": "Rooftop premium del Hilton, con vista y menú de bar/restaurante.",
    "how": "Caminata por la orla o Uber corto.",
    "safety": "Zona cómoda.",
    "tip": "Upgrade opcional si quieren una noche más cuidada.",
    "source": "https://www.hilton.com/en-gb/hotels/riocchh-hilton-rio-de-janeiro-copacabana/dining/isabel-lounge/",
    "sourceLabel": "Hilton · oficial",
    "profile": "beachNight",
    "confidence": "Oficial / consumo variable",
    "steps": [
      "Base",
      "Leme",
      "Hilton",
      "Isabel Lounge"
    ]
  },
  {
    "id": "armazem_senado",
    "cat": "Noche",
    "icon": "🎶",
    "name": "Armazém do Senado / Rua do Senado",
    "zone": "Centro / Lapa",
    "price": "Consumo",
    "duration": "2–4 h",
    "dist": "9 km",
    "time": "25–35 min",
    "transport": "Uber",
    "ret": "Uber",
    "info": "Alternativa de samba más tranquila a Pedra do Sal, mencionada en reels como plan con música en vivo y caipirinha.",
    "how": "Uber directo; combinar con Centro/Lapa si aún están de día.",
    "safety": "Mejor ir al lugar puntual y volver en Uber.",
    "tip": "Buena alternativa si Pedra do Sal está demasiado lleno.",
    "source": "https://www.instagram.com/reel/DUGi58ajdzu/",
    "sourceLabel": "Reel de referencia",
    "profile": "centerNight",
    "confidence": "Reel / revalidar agenda",
    "steps": [
      "Base",
      "Rua do Senado",
      "Armazém / samba",
      "Uber regreso"
    ]
  },
  {
    "id": "beco_rato",
    "cat": "Noche",
    "icon": "🎶",
    "name": "Beco do Rato",
    "zone": "Lapa",
    "price": "Entrada/consumo variable",
    "duration": "3–5 h",
    "dist": "8–9 km",
    "time": "25–35 min",
    "transport": "Uber",
    "ret": "Uber",
    "info": "Otro spot de samba/pagode mencionado como recomendación local en los comentarios de los reels.",
    "how": "Uber directo o combinar con Lapa.",
    "safety": "Volver en Uber si termina tarde.",
    "tip": "Candidato secundario, revalidar programación semanal.",
    "source": "https://www.instagram.com/reel/DXzKs5cASfo/",
    "sourceLabel": "Reel / comentarios",
    "profile": "lapa",
    "confidence": "Recomendación comunitaria",
    "steps": [
      "Base",
      "Lapa",
      "Beco do Rato",
      "Uber regreso"
    ]
  },
  {
    "id": "via_onze",
    "cat": "Noche",
    "icon": "🎶",
    "name": "Via Onze",
    "zone": "Barra da Tijuca",
    "price": "Consumo / evento variable",
    "duration": "2–4 h",
    "dist": "Lejos",
    "time": "35–60 min",
    "transport": "Uber",
    "ret": "Uber",
    "info": "Bar de playa / música en vivo al atardecer mencionado en reel de samba/pagode.",
    "how": "Uber; está bastante más lejos de Copacabana.",
    "safety": "La logística pesa más que el riesgo. No conviene si el presupuesto de traslados está apretado.",
    "tip": "Solo lo priorizaría si ya tienen otro motivo para ir a Barra.",
    "source": "https://www.instagram.com/reel/DXzKs5cASfo/",
    "sourceLabel": "Reel de referencia",
    "profile": "west",
    "confidence": "Reel / revalidar",
    "steps": [
      "Base",
      "Barra da Tijuca",
      "Via Onze",
      "Uber regreso"
    ]
  },
  {
    "id": "salgueiro",
    "cat": "Noche",
    "icon": "🥁",
    "name": "Escola de Samba Salgueiro · ensayo/evento",
    "zone": "Tijuca",
    "price": "R$30–60 aprox · revisar",
    "duration": "3–5 h",
    "dist": "12 km",
    "time": "30–45 min",
    "transport": "Uber",
    "ret": "Uber",
    "info": "Experiencia de escuela de samba, muy distinta a bar/boliche. Aparece en reels como opción de samba auténtica.",
    "how": "Uber directo y volver en Uber.",
    "safety": "Plan de evento; revisar fecha, horario y venta oficial.",
    "tip": "Si coincide ensayo abierto, puede ser de las experiencias culturales más memorables.",
    "source": "https://www.instagram.com/reel/DXzKs5cASfo/",
    "sourceLabel": "Reel de referencia",
    "profile": "center",
    "confidence": "Agenda a revalidar",
    "steps": [
      "Base",
      "Tijuca",
      "Quadra do Salgueiro",
      "Uber regreso"
    ]
  },
  {
    "id": "boma",
    "cat": "Noche",
    "icon": "🎧",
    "name": "BOMA / fiesta en área externa del Museu do Amanhã",
    "zone": "Praça Mauá",
    "price": "Variable / normalmente alto",
    "duration": "5–8 h",
    "dist": "10 km",
    "time": "25–35 min",
    "transport": "Uber",
    "ret": "Uber",
    "info": "Fiestas grandes de electrónica asociadas al Museu do Amanhã. La organización aclara que se hacen en el área externa, no dentro del museo.",
    "how": "Uber ida y vuelta.",
    "safety": "No asumir que habrá fecha justo en marzo 2027. Si hay, resolver regreso antes de entrar.",
    "tip": "Solo agregar si coincide una fecha fuerte con el viaje.",
    "source": "https://www.weareboma.com.br/",
    "sourceLabel": "BOMA · oficial",
    "profile": "centerNight",
    "confidence": "Oficial / evento eventual",
    "steps": [
      "Base",
      "Praça Mauá",
      "Área externa Museu do Amanhã",
      "Uber regreso"
    ]
  },
  {
    "id": "boat_party",
    "cat": "Noche",
    "icon": "⛵",
    "name": "Boat Party · Bem Brasil / similares",
    "zone": "Marina / Bahía de Guanabara",
    "price": "Reel: R$150–250 · verificar",
    "duration": "4–6 h",
    "dist": "Variable",
    "time": "Según embarque",
    "transport": "Uber + barco",
    "ret": "Uber",
    "info": "Fiesta en barco al atardecer o madrugada. En reels aparece como una de las experiencias nocturnas más diferentes.",
    "how": "Confirmar muelle, horario de embarque y regreso antes de comprar.",
    "safety": "No improvisar muelle ni comprar por canales dudosos. Llevar batería y tener Uber de regreso resuelto.",
    "tip": "Gran extra si el presupuesto aguanta y hay fecha compatible.",
    "source": "https://www.instagram.com/reel/DYkrLB4xLJ0/",
    "sourceLabel": "Reel de referencia",
    "profile": "urca",
    "confidence": "Evento variable / revalidar",
    "steps": [
      "Base",
      "Muelle del evento",
      "Boat Party",
      "Regreso al muelle",
      "Uber"
    ]
  },
  {
    "id": "cinema_party",
    "cat": "Noche",
    "icon": "🎬",
    "name": "Fiesta en cine · Playground / evento eventual",
    "zone": "Río · sede variable",
    "price": "Variable",
    "duration": "4–6 h",
    "dist": "Variable",
    "time": "Según evento",
    "transport": "Uber",
    "ret": "Uber",
    "info": "Fiesta dentro de un cine mencionada en reels. No es un evento semanal estable: depende de agenda.",
    "how": "Solo planearla si aparece fecha confirmada en la semana del viaje.",
    "safety": "Usar canal oficial del evento y confirmar venue exacto.",
    "tip": "Guardar como wishlist, no como plan fijo.",
    "source": "https://www.instagram.com/reel/DYkrLB4xLJ0/",
    "sourceLabel": "Reel de referencia",
    "profile": "night",
    "confidence": "Evento eventual",
    "steps": [
      "Base",
      "Venue confirmado",
      "Fiesta",
      "Uber regreso"
    ]
  },
  {
    "id": "vizta_mercure",
    "cat": "Noche",
    "icon": "🌇",
    "name": "Vizta Rooftop · Mercure Copacabana",
    "zone": "Copacabana",
    "price": "Consumo variable",
    "duration": "2–4 h",
    "dist": "En el barrio",
    "time": "5–15 min",
    "transport": "A pie / Uber corto",
    "ret": "A pie / Uber",
    "info": "Rooftop en Copacabana para tomar algo con vista, sumado a partir de las referencias del chat. Es una opción flexible, no una reserva cerrada.",
    "how": "Confirmar acceso, horario y si exige reserva antes de ir. Desde la base debería resolverse caminando o con un Uber corto.",
    "safety": "Plan cercano a la base. Para la vuelta tarde, evitar caminar con el celular visible y usar Uber si están cansados.",
    "tip": "Sirve como plan corto de atardecer o previa, sin bloquear toda la noche.",
    "source": "https://all.accor.com/",
    "sourceLabel": "Accor · referencia oficial",
    "profile": "beach",
    "confidence": "Revalidar horarios",
    "steps": [
      "Base en Copacabana",
      "Mercure Copacabana",
      "Vizta Rooftop",
      "Regreso a la base"
    ]
  }
];
